ci: Add summary job for CIs

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -39,3 +39,20 @@ jobs:
 
       - name: Check markdown formatting
         run: prettier --check '**.md' '**.yml'
+
+  # Summary job that depends on all other jobs
+  lint-ci-success:
+    name: CI Success
+    runs-on: ubuntu-latest
+    needs: [changes, lint]
+    if: always()
+    steps:
+      - name: Check all jobs status
+        run: |
+          if [[ "${{ needs.changes.result }}" == "failure" ||
+                "${{ needs.lint.result }}" == "failure" ]]; then
+            echo "One or more jobs failed"
+            exit 1
+          else
+            echo "All jobs passed or were skipped"
+          fi
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -104,3 +104,22 @@ jobs:
           tool: cargo-udeps
       - name: Run cargo +nightly udeps
         run: cargo +nightly udeps --release --workspace --all-targets --all-features
+
+  # Summary job that depends on all other jobs
+  rust-ci-success:
+    name: CI Success
+    runs-on: ubuntu-latest
+    needs: [changes, lint-and-test, build-cross-platform, test-on-nightly]
+    if: always()
+    steps:
+      - name: Check all jobs status
+        run: |
+          if [[ "${{ needs.changes.result }}" == "failure" ||
+                "${{ needs.lint-and-test.result }}" == "failure" ||
+                "${{ needs.build-cross-platform.result }}" == "failure" ||
+                "${{ needs.test-on-nightly.result }}" == "failure" ]]; then
+            echo "One or more jobs failed"
+            exit 1
+          else
+            echo "All jobs passed or were skipped"
+          fi
